M48
; DRILL file {KiCad 9.0.6} date 2025-11-19T18:33:37-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-19T18:33:37-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C2.000
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C4.000
%
G90
G05
T1
X145.0Y-106.501
T2
X158.0Y-108.0
T3
X162.5Y-121.0
M30
